# Generated by Django 6.1 on 2026-08-24 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier for the category, used in URLs.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="The order in which the category should be displayed. Lower numbers will be displayed first.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier for the product, used in URLs.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="The order in which the product should be displayed. Lower numbers will be displayed first.",
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("in_sale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products", to="products.category"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
