# Generated by Django 6.1 on 2026-09-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_out",
            field=models.BooleanField(default=False),
        ),
    ]
