# Generated by Django 6.1 on 2026-09-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_sold_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
